version: '3.9'

services:
  djangoapp:
    container_name: djangoapp
    build:
      context: .
      dockerfile: ./Dockerfile  # Corrigindo o nome da propriedade para 'dockerfile'
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env
